services:
  ros-desktop:
    image: osrf/ros:kilted-desktop-full
    profiles:
      - dev
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri
  gazebo:
    image: gazebo
    command:
      - gzserver
    profiles:
      - dev
