theme = 'gruvbox'

[editor]
auto-format = true
true-color = true

[editor.whitespace]
render = 'all'

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false # this actually *enables* hidden files ffs
